-- KAASFIELD FARMS | Neon PostgreSQL schema
create extension if not exists pgcrypto;
create type public.app_role as enum ('admin', 'farm_manager', 'staff', 'veterinarian');
create type public.record_status as enum ('active', 'sold', 'deceased', 'sick', 'quarantined', 'archived');
create type public.inventory_transaction_type as enum ('purchase', 'usage', 'adjustment', 'sale', 'loss', 'expired');

create table public.profiles (id uuid primary key default gen_random_uuid(), full_name text not null, email text not null unique, password_hash text not null, role public.app_role not null default 'staff', department text, phone text, status text not null default 'active' check (status in ('active','inactive')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.suppliers (id uuid primary key default gen_random_uuid(), supplier_id text not null unique, name text not null, contact_person text, phone text, email text, address text, products_supplied text[], notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.livestock (id uuid primary key default gen_random_uuid(), animal_id text not null unique, animal_type text not null check (animal_type in ('Cow','Goat','Ram','Chicken','Duck','Pig','Other')), breed text, sex text check (sex in ('Male','Female','Mixed','Unknown')), quantity integer not null default 1 check (quantity > 0), date_acquired date, source text, purchase_cost numeric(14,2) not null default 0 check (purchase_cost >= 0), current_status public.record_status not null default 'active', location text, weight numeric(10,2) check (weight >= 0), date_of_birth date, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.crop_plots (id uuid primary key default gen_random_uuid(), plot_id text not null unique, plot_name text not null, crop_name text not null, variety text, area numeric(12,2) not null default 0 check (area >= 0), area_unit text not null default 'ha', planting_date date, number_of_plants integer check (number_of_plants >= 0), current_stage text, expected_harvest_date date, status text not null default 'active' check (status in ('active','completed','fallow','archived')), notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.inventory (id uuid primary key default gen_random_uuid(), item_id text not null unique, item_name text not null, category text not null check (category in ('Feed','Medication','Vaccine','Pesticide','Fungicide','Fertilizer','Seeds','Equipment','Other')), quantity numeric(14,2) not null default 0 check (quantity >= 0), unit text not null, minimum_stock numeric(14,2) not null default 0 check (minimum_stock >= 0), purchase_date date, expiry_date date, supplier_id uuid references public.suppliers(id), cost numeric(14,2) not null default 0 check (cost >= 0), storage_location text, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.animal_health_records (id uuid primary key default gen_random_uuid(), record_id text not null unique, livestock_id uuid not null references public.livestock(id), record_date date not null default current_date, condition text, symptoms text, diagnosis text, treatment text, medication text, dosage text, route text, veterinarian_staff uuid references public.profiles(id), cost numeric(14,2) not null default 0 check (cost >= 0), treatment_start_date date, treatment_end_date date, next_checkup_date date, outcome text, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.vaccinations (id uuid primary key default gen_random_uuid(), vaccination_id text not null unique, livestock_id uuid not null references public.livestock(id), vaccine text not null, vaccination_date date not null default current_date, bird_age text, quantity_treated integer not null check (quantity_treated > 0), dosage text, purpose text, staff_responsible uuid references public.profiles(id), next_vaccination_date date, cost numeric(14,2) not null default 0 check (cost >= 0), notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.feeds (id uuid primary key default gen_random_uuid(), feed_id text not null unique, feed_name text not null, animal_type text not null, quantity numeric(14,2) not null default 0 check (quantity >= 0), unit text not null, supplier_id uuid references public.suppliers(id), purchase_date date, expiry_date date, cost numeric(14,2) not null default 0 check (cost >= 0), current_stock numeric(14,2) not null default 0 check (current_stock >= 0), minimum_stock numeric(14,2) not null default 0 check (minimum_stock >= 0), notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.inventory_transactions (id uuid primary key default gen_random_uuid(), inventory_id uuid not null references public.inventory(id), transaction_type public.inventory_transaction_type not null, quantity numeric(14,2) not null check (quantity > 0), reference_type text, reference_id uuid, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.feed_usage (id uuid primary key default gen_random_uuid(), feed_id uuid not null references public.feeds(id), quantity numeric(14,2) not null check (quantity > 0), usage_date date not null default current_date, livestock_id uuid references public.livestock(id), notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.crop_applications (id uuid primary key default gen_random_uuid(), application_id text not null unique, plot_id uuid not null references public.crop_plots(id), application_date date not null default current_date, growth_stage text, product_name text not null, product_type text not null check (product_type in ('Pesticide','Fungicide','Herbicide','Fertilizer','Other')), active_ingredient text, dosage text, water_volume text, area_treated numeric(12,2) check (area_treated >= 0), purpose text, staff_responsible uuid references public.profiles(id), cost numeric(14,2) not null default 0 check (cost >= 0), next_application_date date, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.harvests (id uuid primary key default gen_random_uuid(), harvest_id text not null unique, plot_id uuid not null references public.crop_plots(id), crop text not null, harvest_date date not null default current_date, quantity numeric(14,2) not null check (quantity > 0), unit text not null, grade text, quality text, staff uuid references public.profiles(id), storage_location text, selling_price numeric(14,2) not null default 0 check (selling_price >= 0), notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.sales (id uuid primary key default gen_random_uuid(), sale_id text not null unique, sale_date date not null default current_date, product text not null, crop_livestock text, quantity numeric(14,2) not null check (quantity > 0), unit text not null, unit_price numeric(14,2) not null check (unit_price >= 0), total_amount numeric(14,2) generated always as (quantity * unit_price) stored, customer text, payment_status text not null default 'Pending' check (payment_status in ('Paid','Pending','Partially Paid')), payment_method text, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.expenses (id uuid primary key default gen_random_uuid(), expense_id text not null unique, expense_date date not null default current_date, category text not null, description text not null, department text, quantity numeric(14,2) not null default 1 check (quantity > 0), unit_cost numeric(14,2) not null check (unit_cost >= 0), total_cost numeric(14,2) generated always as (quantity * unit_cost) stored, supplier_id uuid references public.suppliers(id), payment_status text not null default 'Paid' check (payment_status in ('Paid','Pending','Partially Paid')), payment_method text, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.staff (id uuid primary key default gen_random_uuid(), staff_id text not null unique, profile_id uuid unique references public.profiles(id), name text not null, phone text, email text, role public.app_role not null default 'staff', department text, date_joined date, status text not null default 'active' check (status in ('active','inactive')), notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.activity_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, description text not null, created_at timestamptz not null default now());

create index livestock_status_idx on public.livestock(current_status); create index livestock_type_idx on public.livestock(animal_type); create index health_livestock_idx on public.animal_health_records(livestock_id, record_date desc); create index vaccination_due_idx on public.vaccinations(next_vaccination_date); create index inventory_category_idx on public.inventory(category); create index inventory_expiry_idx on public.inventory(expiry_date); create index application_plot_idx on public.crop_applications(plot_id, application_date desc); create index harvest_plot_idx on public.harvests(plot_id, harvest_date desc); create index expenses_date_idx on public.expenses(expense_date desc); create index sales_date_idx on public.sales(sale_date desc); create index activity_created_idx on public.activity_logs(created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create or replace function public.apply_inventory_transaction() returns trigger language plpgsql security definer set search_path = public as $$ declare delta numeric; begin delta := case when new.transaction_type in ('purchase','adjustment') then new.quantity else -new.quantity end; update public.inventory set quantity = quantity + delta where id = new.inventory_id and quantity + delta >= 0; if not found then raise exception 'Inventory quantity cannot become negative'; end if; return new; end; $$;
create trigger inventory_transaction_stock before insert on public.inventory_transactions for each row execute function public.apply_inventory_transaction();

do $$ declare t text; begin foreach t in array array['profiles','suppliers','livestock','crop_plots','inventory','animal_health_records','vaccinations','feeds','feed_usage','crop_applications','harvests','sales','expenses','staff'] loop execute format('create trigger %I before update on public.%I for each row execute function public.touch_updated_at()', t || '_touch', t); end loop; end $$;

insert into public.suppliers (supplier_id, name, contact_person, phone, products_supplied) values ('SUP-001','Green Valley Agro','Musa Bello','08000000000',array['Feed','Medication','Fertilizer']) on conflict do nothing;
insert into public.livestock (animal_id, animal_type, breed, sex, quantity, date_acquired, source, current_status, location) values ('GOAT-G001','Goat','West African Dwarf','Mixed',25,'2026-09-14','Farm','active','Goat pen'),('RAM-R001','Ram','Yankasa','Male',10,'2026-09-14','Farm','active','Small ruminant pen'),('COW-C001','Cow','White Fulani','Female',8,'2026-09-14','Farm','active','Cattle yard'),('CH-B001','Chicken','Broiler','Mixed',300,'2026-09-14','Hatchery','active','Poultry house 1'),('DUCK-D001','Duck','Local','Mixed',15,'2026-09-14','Farm','active','Duck shelter') on conflict do nothing;
insert into public.crop_plots (plot_id, plot_name, crop_name, variety, area, number_of_plants, current_stage, expected_harvest_date) values ('P001','Tomato Plot A','Tomato','Roma',0.5,1200,'Vegetative','2026-10-12'),('P002','Tomato Plot B','Tomato','Roma',0.4,950,'Flowering','2026-10-03') on conflict do nothing;
insert into public.inventory (item_id, item_name, category, quantity, unit, minimum_stock, purchase_date, storage_location) values ('I001','Broiler Feed','Feed',48,'bags',10,'2026-09-14','Feed store'),('I002','Poultry Vaccine','Vaccine',300,'doses',100,'2026-09-14','Cold cabinet'),('I003','Tomato Fungicide','Fungicide',1,'litres',2,'2026-09-14','Chemical store') on conflict do nothing;

